(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ShizukuB2B=api;})(typeof globalThis==='object'?globalThis:this,function(){
 const statuses=['preparing','on_the_way','delivered','completed'];
 const labels={preparing:'Preparing',on_the_way:'On the way',delivered:'Delivered',completed:'Completed'};
 const fields=[['recipient_name','Recipient Name',true],['contact_number','Contact Number',true],['business_name','Business Name (optional)',false],['address_line_1','Address Line 1',true],['address_line_2','Address Line 2',false],['postal_code','Postal Code',true],['delivery_notes','Delivery Notes',false]];
 function classify(lines,products){const flags=lines.map(l=>products.find(p=>String(p.id)===String(l.productId??l.product_id))?.is_b2b===true);return !flags.length?'empty':flags.every(Boolean)?'b2b':flags.some(Boolean)?'mixed':'drinks';}
 function addressError(a,market){for(const [k,label,required] of fields)if(required&&!String(a?.[k]||'').trim())return `Please enter ${label}.`;if(market==='SG'&&!/^\d{6}$/.test(String(a.postal_code||'').trim()))return 'Please enter a 6-digit Singapore postal code.';return '';}
 function addressText(a){return fields.filter(([k])=>k!=='delivery_notes').map(([k])=>String(a?.[k]||'').trim()).filter(Boolean).join('\n');}
 function next(order){if(order.payment_status!=='paid')return null;return statuses[statuses.indexOf(order.order_status)+1]||null;}
 function whatsapp(o){const intro=o.order_status==='on_the_way'?`Hi ${o.customer_name||'there'}! Your Shizuku Lab order is on the way 🤍`:o.order_status==='delivered'||o.order_status==='completed'?`Hi ${o.customer_name||'there'}! Your Shizuku Lab order has been delivered 🤍 Thank you for your support.`:`Hi ${o.customer_name||'there'}! Your Shizuku Lab B2B order is confirmed 🤍 Free Delivery is included.`;return [intro,...(o.order_status==='on_the_way'?[o.courier?`Courier: ${o.courier}`:'',o.tracking_number?`Tracking Number: ${o.tracking_number}`:'']:[])].filter(Boolean).join('\n');}
 function whatsappUrl(o){let digits=String(o.customer_phone||'').replace(/\D/g,'');if(digits.startsWith('00'))digits=digits.slice(2);if(String(o.market_code||'SG').toUpperCase()==='MY'){if(digits.startsWith('0'))digits='60'+digits.slice(1);if(!/^60[1-9]\d{7,10}$/.test(digits))return '';}else{if(digits.length===8)digits='65'+digits;if(!/^65[689]\d{7}$/.test(digits))return '';}return 'https://wa.me/'+digits+'?text='+encodeURIComponent(whatsapp(o));}
 function invoice(o,items,money){const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const rows=items.map(i=>{const q=Number(i.quantity??i.qty??1),p=Number(i.unit_price??i.unitPrice??0);return `<tr><td>${esc(i.product_name??i.productName??'Product')}</td><td>${q}</td><td>${esc(money(p))}</td><td>${esc(money(q*p))}</td></tr>`;}).join('');const subtotal=items.reduce((s,i)=>s+Number(i.quantity??i.qty??1)*Number(i.unit_price??i.unitPrice??0),0),discount=Math.max(0,subtotal-Number(o.total||0));return `<div class="summary-card receipt-card"><h2>SHIZUKU LAB</h2><h1>INVOICE</h1><p>Invoice Number: <b>${esc(o.invoice_number||'Pending invoice number')}</b><br>Order Number: ${esc(o.order_number)}<br>Invoice Date: ${esc(String(o.invoice_date||o.created_at||'').slice(0,10))}</p><p>${esc(o.delivery_address?.business_name||'')}<br>Customer Name: ${esc(o.customer_name)}<br>Contact: ${esc(o.customer_phone)}</p><p><b>Delivery Address</b><br>${esc(addressText(o.delivery_address)).replace(/\n/g,'<br>')}</p><div style="overflow:auto"><table style="width:100%;text-align:left"><thead><tr><th>Product</th><th>Quantity</th><th>Unit Price</th><th>Line Total</th></tr></thead><tbody>${rows}</tbody></table></div><div class="divider"></div><div class="row"><span>Subtotal</span><b>${esc(money(subtotal))}</b></div>${discount?`<div class="row"><span>Discount</span><b>−${esc(money(discount))}</b></div>`:''}<div class="row"><span>Delivery</span><b>FREE</b></div><div class="row bold"><span>Total</span><b>${esc(money(o.total))}</b></div><p>Payment Status: <b>${o.payment_status==='paid'?'PAID':'UNPAID'}</b></p></div>`;}
 return {statuses,labels,fields,classify,addressError,addressText,next,whatsapp,whatsappUrl,invoice};
});
