(() => {
  const cfg=window.SHIZUKU_SUPABASE||{};
  const client=window.supabase&&cfg.url&&cfg.anonKey?window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
  const form=document.getElementById('accountForm'),title=document.getElementById('accountTitle'),kicker=document.getElementById('accountKicker'),intro=document.getElementById('accountIntro'),confirmField=document.getElementById('confirmField'),submit=document.getElementById('accountSubmit'),modeSwitch=document.getElementById('modeSwitch'),message=document.getElementById('accountMessage');
  let mode=new URLSearchParams(location.search).get('mode')==='create'?'create':'login';
  function showMessage(text,isError=false){message.hidden=!text;message.textContent=text||'';message.classList.toggle('is-error',isError);}
  function paint(){const creating=mode==='create';kicker.textContent=creating?'JOIN SHIZUKU LAB':'SHIZUKU LAB';title.textContent=creating?'Create account':'Welcome back';intro.textContent=creating?'Use the email the Shizuku Lab owner invited.':'Sign in to your Shizuku Lab workspace.';confirmField.hidden=!creating;confirmField.querySelector('input').required=creating;form.password.autocomplete=creating?'new-password':'current-password';form.password.minLength=creating?10:0;submit.textContent=creating?'CREATE ACCOUNT':'LOG IN';modeSwitch.textContent=creating?'Already have an account? Log in':'Invited to Shizuku Lab? Create account';}
  async function destination(){const {data:{user},error}=await client.auth.getUser();if(error||!user)throw error||new Error('Your secure session could not be opened.');
    const email=String(user.email||'').toLowerCase();
    const team=await client.from('studio_users').select('*').ilike('email',email).eq('is_active',true).maybeSingle();
    if(email===String(cfg.adminEmail||'').toLowerCase()){location.href='/workspace-home';return;}
    if(team.data){const market=String(team.data.market_code||team.data.country_code||'SG').toUpperCase();location.href=market==='MY'?'/workspace/shizuku-lab-my':'/workspace/shizuku-lab-sg';return;}
    await client.auth.signOut();throw new Error('No Shizuku Lab invitation was found for this email. Ask the Shizuku Lab owner to invite you first.');
  }
  modeSwitch.addEventListener('click',()=>{mode=mode==='create'?'login':'create';history.replaceState(null,'',`/shizuku-account?mode=${mode}`);form.reset();showMessage('');paint();});
  form.addEventListener('submit',async event=>{event.preventDefault();if(!client)return showMessage('Secure login is temporarily unavailable. Please try again later.',true);const data=new FormData(form),email=String(data.get('email')||'').trim().toLowerCase(),password=String(data.get('password')||'');submit.disabled=true;showMessage('');try{if(mode==='create'){if(password!==String(data.get('confirm')||''))throw new Error('The passwords do not match.');const result=await client.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/shizuku-account?mode=login`}});if(result.error)throw result.error;form.reset();if(result.data.session)await destination();else showMessage('Check your email to confirm your account. Only an email invited by the Shizuku Lab owner can enter.');}else{const result=await client.auth.signInWithPassword({email,password});if(result.error)throw result.error;form.reset();await destination();}}catch(error){console.error('Shizuku authentication failed',error);const code=String(error?.code||'');showMessage(code==='invalid_credentials'?'That email or password is not correct. Please try again.':code==='email_not_confirmed'?'Confirm your email first, then log in.':(error?.message||'Login failed. Please try again.'),true);}finally{form.querySelectorAll('input[type=password]').forEach(input=>input.value='');submit.disabled=false;paint();}});
  paint();
})();
