-- Slow Studio: owner-managed marketing contacts, kept separate by market.
create table if not exists public.marketing_contacts (
  id bigint generated by default as identity primary key,
  market_code text not null default 'SG' check (market_code in ('SG','MY')),
  customer_name text not null,
  customer_email text,
  customer_phone text,
  marketing_email_opt_in boolean not null default false,
  marketing_whatsapp_opt_in boolean not null default false,
  consent_source text not null default 'admin',
  consent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marketing_contacts_detail_check check (nullif(trim(customer_email),'') is not null or nullif(trim(customer_phone),'') is not null)
);

create unique index if not exists marketing_contacts_market_email_unique
  on public.marketing_contacts (market_code, lower(trim(customer_email)))
  where nullif(trim(customer_email),'') is not null;
create index if not exists marketing_contacts_market_created_idx
  on public.marketing_contacts (market_code, created_at desc);

alter table public.marketing_contacts enable row level security;

drop policy if exists marketing_contacts_admin_select on public.marketing_contacts;
drop policy if exists marketing_contacts_admin_insert on public.marketing_contacts;
drop policy if exists marketing_contacts_admin_update on public.marketing_contacts;
drop policy if exists marketing_contacts_admin_delete on public.marketing_contacts;
create policy marketing_contacts_admin_select on public.marketing_contacts for select to authenticated using ((select public.is_shizuku_admin()));
create policy marketing_contacts_admin_insert on public.marketing_contacts for insert to authenticated with check ((select public.is_shizuku_admin()));
create policy marketing_contacts_admin_update on public.marketing_contacts for update to authenticated using ((select public.is_shizuku_admin())) with check ((select public.is_shizuku_admin()));
create policy marketing_contacts_admin_delete on public.marketing_contacts for delete to authenticated using ((select public.is_shizuku_admin()));

revoke all on table public.marketing_contacts from public, anon;
grant select, insert, update, delete on table public.marketing_contacts to authenticated, service_role;
grant usage, select on sequence public.marketing_contacts_id_seq to authenticated, service_role;

create or replace function public.send_marketing_campaign_email(p_customer_email text, p_market_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  contact record;
  campaign record;
  notify record;
  request_id bigint;
  normalized_email text := lower(trim(coalesce(p_customer_email, '')));
  normalized_market text := upper(trim(coalesce(p_market_code, 'SG')));
begin
  if not public.is_shizuku_admin() then raise exception 'Not authorised'; end if;
  if normalized_market not in ('SG','MY') then raise exception 'Invalid market'; end if;
  if normalized_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then raise exception 'Invalid email address'; end if;

  select m.customer_name, m.customer_email into contact
  from public.marketing_contacts m
  where lower(trim(coalesce(m.customer_email, ''))) = normalized_email
    and m.market_code = normalized_market
    and m.marketing_email_opt_in = true
  order by coalesce(m.consent_at, m.created_at) desc
  limit 1;

  if not found then
    select o.customer_name, o.customer_email into contact
    from public.orders o
    where lower(trim(coalesce(o.customer_email, ''))) = normalized_email
      and upper(coalesce(o.market_code, 'SG')) = normalized_market
      and o.marketing_email_opt_in = true
    order by coalesce(o.marketing_consent_at, o.created_at) desc
    limit 1;
  end if;
  if not found then raise exception 'Customer has not opted in to email marketing'; end if;

  select s.marketing_email_subject, s.marketing_email_body,
         s.marketing_attachment_url, s.marketing_attachment_name, s.marketing_attachment_type
  into campaign from public.store_settings s order by s.created_at limit 1;
  select n.webhook_url into notify from public.notification_settings n where n.id = 1;
  if nullif(trim(coalesce(notify.webhook_url, '')), '') is null then raise exception 'Email webhook is not configured'; end if;

  select net.http_post(
    url := notify.webhook_url,
    headers := jsonb_build_object('Content-Type','application/json'),
    body := jsonb_build_object(
      'event','marketing_campaign', 'send_owner',false, 'customer_email',contact.customer_email,
      'customer_name',contact.customer_name, 'market_code',normalized_market,
      'marketing_email_subject',campaign.marketing_email_subject,
      'marketing_email_body',campaign.marketing_email_body, 'attachment_url',campaign.marketing_attachment_url,
      'attachment_name',campaign.marketing_attachment_name, 'attachment_type',campaign.marketing_attachment_type
    )
  ) into request_id;
  return jsonb_build_object('ok',true,'queued',true,'request_id',request_id);
end;
$$;

revoke all on function public.send_marketing_campaign_email(text,text) from public, anon;
grant execute on function public.send_marketing_campaign_email(text,text) to authenticated, service_role;
