-- Shizuku Lab: verified customer reviews with admin moderation.
-- Run this file once in Supabase SQL Editor, then deploy the updated site files.

create table if not exists public.customer_reviews (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  order_number text not null,
  customer_name text not null,
  rating smallint not null check (rating between 1 and 5),
  review_text text not null check (char_length(review_text) between 3 and 600),
  status text not null default 'pending' check (status in ('pending', 'published', 'hidden')),
  created_at timestamptz not null default now(),
  published_at timestamptz
);

alter table public.customer_reviews enable row level security;

drop policy if exists "Anyone can read published reviews" on public.customer_reviews;
create policy "Anyone can read published reviews"
on public.customer_reviews for select
using (status = 'published' or (auth.role() = 'authenticated' and coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false));

drop policy if exists "Admins can moderate reviews" on public.customer_reviews;
create policy "Admins can moderate reviews"
on public.customer_reviews for update
to authenticated
using (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false)
with check (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false);

drop policy if exists "Admins can delete reviews" on public.customer_reviews;
create policy "Admins can delete reviews"
on public.customer_reviews for delete
to authenticated
using (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false);

create or replace function public.submit_shizuku_review(
  p_order_number text,
  p_phone text,
  p_customer_name text,
  p_rating integer,
  p_review_text text
)
returns public.customer_reviews
language plpgsql
security definer
set search_path = public
as $$
declare
  matched_order public.orders%rowtype;
  new_review public.customer_reviews;
  phone_digits text := regexp_replace(coalesce(p_phone, ''), '[^0-9]', '', 'g');
begin
  if p_rating < 1 or p_rating > 5 then raise exception 'Choose a rating from 1 to 5.'; end if;
  if char_length(trim(coalesce(p_review_text, ''))) < 3 then raise exception 'Please write a little more about your visit.'; end if;

  select * into matched_order
  from public.orders
  where upper(order_number) = upper(trim(p_order_number))
    and regexp_replace(coalesce(customer_phone, ''), '[^0-9]', '', 'g') in (phone_digits, regexp_replace(phone_digits, '^65', ''))
  limit 1;

  if matched_order.id is null then raise exception 'Order number and phone number do not match.'; end if;
  if matched_order.payment_status <> 'paid' or matched_order.order_status <> 'collected' then
    raise exception 'Reviews open after a paid order has been collected.';
  end if;

  insert into public.customer_reviews (order_id, order_number, customer_name, rating, review_text)
  values (
    matched_order.id::text,
    matched_order.order_number,
    left(coalesce(nullif(trim(p_customer_name), ''), matched_order.customer_name, 'Customer'), 80),
    p_rating,
    left(trim(p_review_text), 600)
  )
  returning * into new_review;
  return new_review;
exception
  when unique_violation then raise exception 'A review has already been submitted for this order.';
end;
$$;

grant select on public.customer_reviews to anon, authenticated;
grant update, delete on public.customer_reviews to authenticated;
grant usage, select on sequence public.customer_reviews_id_seq to authenticated;
grant execute on function public.submit_shizuku_review(text, text, text, integer, text) to anon, authenticated;
