-- Shizuku Lab: order-linked customer/seller inbox.
-- Run once in Supabase SQL Editor.

create table if not exists public.order_messages (
  id bigint generated by default as identity primary key,
  order_id text not null,
  order_number text not null,
  sender text not null check (sender in ('customer', 'seller')),
  message_text text not null check (char_length(message_text) between 1 and 1000),
  read_by_seller boolean not null default false,
  read_by_customer boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists order_messages_order_id_created_idx on public.order_messages(order_id, created_at);
alter table public.order_messages enable row level security;

drop policy if exists "Admins manage order messages" on public.order_messages;
create policy "Admins manage order messages" on public.order_messages
for all to authenticated
using (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false)
with check (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false);

create or replace function public.get_shizuku_messages(p_order_number text, p_phone text)
returns setof public.order_messages
language plpgsql security definer set search_path = public
as $$
declare matched_id text;
declare phone_digits text := regexp_replace(coalesce(p_phone, ''), '[^0-9]', '', 'g');
begin
  select id::text into matched_id from public.orders
  where upper(order_number) = upper(trim(p_order_number))
    and regexp_replace(coalesce(customer_phone, ''), '[^0-9]', '', 'g') in (phone_digits, regexp_replace(phone_digits, '^65', '')) limit 1;
  if matched_id is null then raise exception 'Order number and phone number do not match.'; end if;
  update public.order_messages set read_by_customer = true where order_id = matched_id and sender = 'seller';
  return query select * from public.order_messages where order_id = matched_id order by created_at;
end; $$;

create or replace function public.send_shizuku_message(p_order_number text, p_phone text, p_message_text text)
returns public.order_messages
language plpgsql security definer set search_path = public
as $$
declare matched_order public.orders%rowtype;
declare new_message public.order_messages;
declare phone_digits text := regexp_replace(coalesce(p_phone, ''), '[^0-9]', '', 'g');
begin
  if char_length(trim(coalesce(p_message_text, ''))) < 1 then raise exception 'Write a message first.'; end if;
  select * into matched_order from public.orders
  where upper(order_number) = upper(trim(p_order_number))
    and regexp_replace(coalesce(customer_phone, ''), '[^0-9]', '', 'g') in (phone_digits, regexp_replace(phone_digits, '^65', '')) limit 1;
  if matched_order.id is null then raise exception 'Order number and phone number do not match.'; end if;
  insert into public.order_messages(order_id, order_number, sender, message_text, read_by_customer)
  values(matched_order.id::text, matched_order.order_number, 'customer', left(trim(p_message_text), 1000), true)
  returning * into new_message;
  return new_message;
end; $$;

grant select, insert, update, delete on public.order_messages to authenticated;
grant usage, select on sequence public.order_messages_id_seq to authenticated;
grant execute on function public.get_shizuku_messages(text, text) to anon, authenticated;
grant execute on function public.send_shizuku_message(text, text, text) to anon, authenticated;

-- Email the seller through the same webhook configured in Admin > Notifications.
create extension if not exists pg_net;
alter table public.notification_settings
add column if not exists alert_live_chat boolean not null default true;
create or replace function public.send_shizuku_message_email()
returns trigger language plpgsql security definer set search_path = public, extensions
as $$
declare settings record;
declare matched_order record;
declare order_items_json jsonb;
begin
  if new.sender <> 'customer' then return new; end if;
  select enabled, webhook_url, recipient_email, alert_live_chat into settings from public.notification_settings where id = 1;
  if not found or not coalesce(settings.enabled, false) or not coalesce(settings.alert_live_chat, true) or nullif(trim(coalesce(settings.webhook_url, '')), '') is null then return new; end if;
  select customer_name, customer_phone into matched_order from public.orders where id::text = new.order_id limit 1;
  select coalesce(jsonb_agg(jsonb_build_object(
    'product_name', oi.product_name,
    'quantity', oi.quantity,
    'unit_price', oi.unit_price
  ) order by oi.id), '[]'::jsonb)
  into order_items_json
  from public.order_items oi
  where oi.order_id::text = new.order_id;
  perform net.http_post(
    url := settings.webhook_url,
    headers := jsonb_build_object('Content-Type', 'application/json'),
    body := jsonb_build_object('event', 'customer_message', 'order_number', new.order_number, 'customer_name', matched_order.customer_name, 'customer_phone', matched_order.customer_phone, 'message_text', new.message_text, 'items', order_items_json)
  );
  return new;
end; $$;

drop trigger if exists shizuku_customer_message_email_alert on public.order_messages;
create trigger shizuku_customer_message_email_alert
after insert on public.order_messages for each row execute function public.send_shizuku_message_email();
