alter table public.store_settings
  add column if not exists track_intro_text text default 'Enter either your order number or the phone number used at checkout.',
  add column if not exists track_order_number_label text default 'Order number',
  add column if not exists track_phone_label text default 'Phone number',
  add column if not exists track_or_text text default 'OR',
  add column if not exists track_button_text text default 'Track order',
  add column if not exists track_live_updates_text text default 'LIVE UPDATES',
  add column if not exists track_refresh_text text default 'Refresh now',
  add column if not exists track_order_label text default 'Order',
  add column if not exists track_pickup_label text default 'Pickup',
  add column if not exists track_stage_payment text default 'Payment review',
  add column if not exists track_stage_confirmed text default 'Confirmed',
  add column if not exists track_stage_preparing text default 'Preparing',
  add column if not exists track_stage_ready text default 'Ready',
  add column if not exists track_awaiting_title text default 'Awaiting payment',
  add column if not exists track_awaiting_note text default 'Please complete payment and submit your payment screenshot.',
  add column if not exists track_review_title text default 'Payment under review',
  add column if not exists track_review_note text default 'We’ll confirm your order once your payment proof is verified.',
  add column if not exists track_confirmed_title text default 'Order confirmed',
  add column if not exists track_confirmed_note text default 'Payment verified — we’ll prepare your order closer to pickup.',
  add column if not exists track_preparing_title text default 'Preparing your order',
  add column if not exists track_preparing_note text default 'We’re freshly preparing your drinks now.',
  add column if not exists track_ready_title text default 'Ready for collection',
  add column if not exists track_ready_note text default 'Your order is ready — see you at your pickup time!',
  add column if not exists track_collected_title text default 'Collected with care ✨',
  add column if not exists track_collected_note text default 'We hope you enjoyed every sip. Looking forward to making your next Shizuku drink.',
  add column if not exists track_cancelled_title text default 'Order cancelled',
  add column if not exists track_cancelled_note text default 'This order can no longer accept payment. Please place a new order.',
  add column if not exists track_rejected_title text default 'Payment proof needs attention',
  add column if not exists track_rejected_note text default 'Please upload a new payment screenshot.';
